set -x
mv out/target/product/morgan3g/boot.img out/target/product/morgan3g/boot.img.
#  /bin/bash -c "(make -j4 -C kernel-4.9-lc O=/home/user/mtksrc/out/target/product/morgan3g/obj/KERNEL_OBJ ARCH=arm CROSS_COMPILE=/home/user/mtksrc/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/bin/arm-linux-androideabi-  ROOTDIR=/home/user/mtksrc ) && (if [ -e /home/user/mtksrc/out/target/product/morgan3g/obj/KERNEL_OBJ/arch/arm/boot/compressed/.piggy.xzkern.cmd ]; then cp /home/user/mtksrc/out/target/product/morgan3g/obj/KERNEL_OBJ/arch/arm/boot/compressed/.piggy.xzkern.cmd /home/user/mtksrc/out/target/product/morgan3g/obj/KERNEL_OBJ/arch/arm/boot/compressed/.piggy.xzkern.cmd.bak; sed -e 's/\\\\\\\\\\\\\\\\/\\\\\\\\/g' < /home/user/mtksrc/out/target/product/morgan3g/obj/KERNEL_OBJ/arch/arm/boot/compressed/.piggy.xzkern.cmd.bak > /home/user/mtksrc/out/target/product/morgan3g/obj/KERNEL_OBJ/arch/arm/boot/compressed/.piggy.xzkern.cmd; rm -f /home/user/mtksrc/out/target/product/morgan3g/obj/KERNEL_OBJ/arch/arm/boot/compressed/.piggy.xzkern.cmd.bak; fi )"
 make -j16 -C kernel-4.9-lc O=/home/user/mtksrc/out/target/product/morgan3g/obj/KERNEL_OBJ ARCH=arm CROSS_COMPILE=/home/user/mtksrc/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/bin/arm-linux-androideabi-  ROOTDIR=/home/user/mtksrc
 if [ -e /home/user/mtksrc/out/target/product/morgan3g/obj/KERNEL_OBJ/arch/arm/boot/compressed/.piggy.xzkern.cmd ]; then cp /home/user/mtksrc/out/target/product/morgan3g/obj/KERNEL_OBJ/arch/arm/boot/compressed/.piggy.xzkern.cmd /home/user/mtksrc/out/target/product/morgan3g/obj/KERNEL_OBJ/arch/arm/boot/compressed/.piggy.xzkern.cmd.bak; sed -e 's/\\\\\\\\\\\\\\\\/\\\\\\\\/g' < /home/user/mtksrc/out/target/product/morgan3g/obj/KERNEL_OBJ/arch/arm/boot/compressed/.piggy.xzkern.cmd.bak > /home/user/mtksrc/out/target/product/morgan3g/obj/KERNEL_OBJ/arch/arm/boot/compressed/.piggy.xzkern.cmd; rm -f /home/user/mtksrc/out/target/product/morgan3g/obj/KERNEL_OBJ/arch/arm/boot/compressed/.piggy.xzkern.cmd.bak; fi 
 /bin/bash -c "(rm -f /home/user/mtksrc/out/target/product/morgan3g/obj/KERNEL_OBJ/arch/arm/boot/zImage-dtb.bin ) && (cp \"/home/user/mtksrc/out/target/product/morgan3g/obj/KERNEL_OBJ/arch/arm/boot/zImage-dtb\" \"/home/user/mtksrc/out/target/product/morgan3g/obj/KERNEL_OBJ/arch/arm/boot/zImage-dtb.bin\" )"
 /bin/bash -c "(rm -f out/target/product/morgan3g/kernel ) && (cp \"/home/user/mtksrc/out/target/product/morgan3g/obj/KERNEL_OBJ/arch/arm/boot/zImage-dtb.bin\" \"out/target/product/morgan3g/kernel\" )"
 /bin/bash -c "(out/host/linux-x86/bin/mkbootimg  --kernel out/target/product/morgan3g/kernel --base 0x80000000 --cmdline \"bootopt=64S3,32S1,32S1 buildvariant=userdebug\" --os_version 9 --os_patch_level 2019-07-05 --kernel_offset 0x00008000 --ramdisk_offset 0x04000000 --tags_offset 0xE000000 --header_version 1 --output out/target/product/morgan3g/obj/PACKAGING/boot_intermediates/boot.img ) && (size=\$(for i in out/target/product/morgan3g/obj/PACKAGING/boot_intermediates/boot.img; do stat --format \"%s\" \"\$i\" | tr -d '\\n'; echo +; done; echo 0); total=\$(( \$( echo \"\$size\" ) )); printname=\$(echo -n \"out/target/product/morgan3g/obj/PACKAGING/boot_intermediates/boot.img\" | tr \" \" +); maxsize=\$((   16777216-69632)); if [ \"\$total\" -gt \"\$maxsize\" ]; then echo \"error: \$printname too large (\$total > \$maxsize)\"; false; elif [ \"\$total\" -gt \$((maxsize - 32768)) ]; then echo \"WARNING: \$printname approaching size limit (\$total now; limit \$maxsize)\"; fi ) && (out/host/linux-x86/bin/avbtool add_hash_footer 	  --image out/target/product/morgan3g/obj/PACKAGING/boot_intermediates/boot.img 	  --partition_size 16777216 	  --partition_name boot )"
 /bin/bash -c "(rm -f out/target/product/morgan3g/boot.img ) && (cp \"out/target/product/morgan3g/obj/PACKAGING/boot_intermediates/boot.img\" \"out/target/product/morgan3g/boot.img\" )"
